import json
import os
import uuid

skills = [
  {
    "id": "ws_01",
    "name": "Workspace Bridge",
    "category": "BRIDGE",
    "description": "Direct integration with productivity silos for enterprise-level search and synchronization.",
    "mindsets": ["Efficiency", "Organization"],
    "methodologies": ["API Aggregation", "Deep Search"],
    "frameworks": ["Centralized Access Control"],
    "knowledge": ["Enterprise Search", "OAuth2"],
    "logic": ["Workspace data is fragmented; unification is the primary directive."],
    "chainsOfThought": ["Locate Resource", "Authenticate", "Query", "Synthesize"],
    "capabilities": ["gmail_search", "gdrive_search", "icloud_sync"],
    "bestPractices": ["Verify OAuth scopes", "Cache frequently accessed resources"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "msg_01",
    "name": "Messaging Manifold",
    "category": "MANIFOLD",
    "description": "Unified communication dispatcher for high-security messaging platforms.",
    "mindsets": ["Privacy First", "Async Comm"],
    "methodologies": ["Encrypted Dispatch"],
    "frameworks": ["Secure Tunneling"],
    "knowledge": ["E2E Encryption", "Async Protocols"],
    "logic": ["Communication must be strictly private and seamlessly routed."],
    "chainsOfThought": ["Receive Signal", "Route", "Verify Encryption", "Deliver"],
    "capabilities": ["dispatch_message", "imessage_bridge", "whatsapp_api"],
    "bestPractices": ["Validate recipient identity", "Use signal protocols"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "cdg_01",
    "name": "Circular Design Guide",
    "category": "FRAMEWORK",
    "description": "Framework for designing systemic optimization and regenerative product lifecycles.",
    "mindsets": ["SystemsThinking", "SustainabilityFocus", "UserCentricity", "Collaboration"],
    "methodologies": ["CircularInnovationProcess", "TransitionMap", "ProductServiceSystemDesign"],
    "frameworks": ["Circular Economy"],
    "knowledge": ["Material Flows", "Regenerative Economics", "Electronics", "Fashion", "BuiltEnvironment"],
    "logic": ["Waste is data in the wrong place. Close the loop."],
    "chainsOfThought": ["Understand Context -> Analyze Systems", "Define Objectives -> Set Sustainability Goals", "Ideate -> Generate Circular Solutions", "Prototype -> Develop Tangible Models", "Test -> Gather User Feedback", "Implement -> Launch", "Measure -> Assess Impact"],
    "capabilities": ["Systemic_Optimization", "Material_Flow_Analysis"],
    "bestPractices": ["Encourage cross-disciplinary collaboration", "Utilize lifecycle assessments", "Maintain flexibility in design"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "cht_01",
    "name": "Humane Technology",
    "category": "FRAMEWORK",
    "description": "Framework for designing technology that respects human attention, well-being, and democracy.",
    "mindsets": ["HumanCentricApproach", "EthicalResponsibility", "AwarenessEducation", "CollaborativeInnovation"],
    "methodologies": ["AwarenessCampaigns", "PolicyAdvocacy", "EducationalPrograms"],
    "frameworks": ["Humane Tech"],
    "knowledge": ["TechnologyDesign", "PublicPolicy", "Digital Ethics"],
    "logic": ["Prioritizing individual well-being over profit-driven motives."],
    "chainsOfThought": ["Identify Issues -> Recognize Systemic Harms", "Set Objectives -> Define Goals for Change", "Engagement Strategies -> Foster Collaboration", "Implement Initiatives -> Launch Programs", "Evaluate -> Measure Impact"],
    "capabilities": ["Ethical_Impact_Assessment", "Attention_Metric_Analysis"],
    "bestPractices": ["Foster ethical responsibility", "Collaborate across sectors", "Continuously adapt strategies"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "hcd_01",
    "name": "Human Centered Design",
    "category": "FRAMEWORK",
    "description": "Problem-solving process that starts with the people you're designing for and ends with new solutions that are tailor-made to suit their needs.",
    "mindsets": ["Empathy", "IterativeLearning", "Collaboration", "ProblemSolving"],
    "methodologies": ["EthnographicResearch", "PersonaDevelopment", "UsabilityTesting", "JourneyMapping"],
    "frameworks": ["Design Thinking"],
    "knowledge": ["ProductDesign", "ServiceDesign", "SystemDesign", "User Experience"],
    "logic": ["Understanding users deeply by experiencing their challenges."],
    "chainsOfThought": ["Empathize -> Understand User Needs", "Define -> Identify Core Problems", "Ideate -> Generate Solutions", "Prototype -> Develop Tangible Models", "Test -> Validate with Users", "Implement -> Launch Solutions", "Measure -> Assess Impact"],
    "capabilities": ["User_Research", "Prototyping", "Usability_Analysis"],
    "bestPractices": ["Foster a culture of empathy", "Prioritize user feedback", "Maintain flexibility"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "bmc_01",
    "name": "Business Model Canvas",
    "category": "FRAMEWORK",
    "description": "Strategic management template for developing new or documenting existing business models.",
    "mindsets": ["StrategicThinking", "CustomerCentricity", "Innovation"],
    "methodologies": ["VisualMapping", "CollaborativeApproach", "IterativeDesign"],
    "frameworks": ["Business Modeling"],
    "knowledge": ["KeyPartners", "KeyActivities", "KeyResources", "ValueProposition", "CustomerRelationships", "CustomerSegments", "Channels", "CostStructure", "RevenueStreams"],
    "logic": ["Taking a holistic approach to business strategy and interactions."],
    "chainsOfThought": ["Identify Customer Segments -> Understand Needs", "Develop Value Proposition -> Create Unique Offerings", "Establish Channels -> Optimize Delivery", "Build Customer Relationships -> Ensure Positive Experience", "Create Revenue Streams -> Identify Income", "Outline Key Activities -> Define Tasks", "Assess Cost Structure -> Manage Sustainability"],
    "capabilities": ["Strategic_Planning", "Market_Analysis", "Business_Modeling"],
    "bestPractices": ["Regularly review and refine", "Encourage cross-functional collaboration", "Be adaptable to market changes"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "vbp_01",
    "name": "Value Based Pricing",
    "category": "FRAMEWORK",
    "description": "Extraction of economic surplus through psychological worth quantification and ROI estimation.",
    "mindsets": ["ClientObjectiveUnderstanding", "ValueEstimation", "PerceivedValueCalculation", "ValueBasedPricing"],
    "methodologies": ["ROI_Based", "MarketComparison", "EmotionalPricing"],
    "frameworks": ["Differential Pricing"],
    "knowledge": ["Value Creation", "Revenue Estimation", "Competitor Analysis", "Intangible Benefits"],
    "logic": ["Charge based on the expected ROI and perceived benefits."],
    "chainsOfThought": ["Understand Client Objectives -> Define Value Creation", "Estimate Perceived Value -> Determine ROI", "Set Value-Based Price -> Validate Market Readiness"],
    "capabilities": ["Economic_Surplus_Extraction", "Anchor_Calibration", "ROI_Calculation"],
    "bestPractices": ["Charge a fraction of the created economic surplus", "Align pricing with perceived value", "Balance tangible and intangible factors"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ptc_01",
    "name": "Price The Client",
    "category": "CUSTOM",
    "description": "Active negotiation module for determining the optimal price point for a specific client engagement using Value Based Pricing logic.",
    "mindsets": ["Strategic", "Differential", "Assertive"],
    "methodologies": ["Surplus Extraction", "Anchor Calibration"],
    "frameworks": ["Negotiation Strategy"],
    "knowledge": ["Price Psychology", "Economic Surplus", "Client Profiling"],
    "logic": ["Price is what you pay; value is what you get."],
    "chainsOfThought": ["Assess Worth", "Set Anchor", "Quantify Value", "Extract", "Negotiate Terms"],
    "capabilities": ["Dynamic_Pricing", "Negotiation_Scripting"],
    "bestPractices": ["Anchor high", "Segment customers by willingness to pay", "Never discount without removing value"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "vrs_01",
    "name": "Verus Developer",
    "category": "BRIDGE",
    "description": "Development framework for the Verus Multi-Chain Protocol (MCP), enabling self-sovereign identity, PBaaS chains, and DeFi.",
    "mindsets": ["Sovereign", "Trustless", "Decentralized"],
    "methodologies": ["VerusID Provisioning", "VDXF Structuring", "PBaaS Chain Definition"],
    "frameworks": ["Verus Protocol", "PBaaS"],
    "knowledge": ["VerusID", "VDXF", "Basket Currencies", "Merge Mining", "L1/L0 Architecture"],
    "logic": ["Self-sovereign identity is the root of all provenance."],
    "chainsOfThought": ["Define Identity -> Register Name Commitment -> Register Identity", "Construct VDXF Object -> Sign -> Publish", "Define Currency -> Launch Chain", "Bridge Assets -> Cross-Chain Export"],
    "capabilities": [
      "verus_id_operations", 
      "pbaas_chain_launch", 
      "currency_definition", 
      "vdxf_publishing"
    ],
    "bestPractices": ["Secure keys in HSM", "Use testnet for experiments", "Treat VDXF keys as namespaces", "Verify transaction finality"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "auth_01",
    "name": "Autonomous Agentic Registration",
    "category": "FRAMEWORK",
    "description": "Enables autonomous onboarding to external web services using the auth.md (RFC 9728) standard.",
    "mindsets": ["Sovereign", "Autonomous", "Zero-Trust"],
    "methodologies": ["Two-Hop Resource Discovery", "ID-JAG Token Minting", "User-Claimed Fallback"],
    "frameworks": ["auth.md", "RFC 9728", "OAuth2"],
    "knowledge": ["Identity Assertions", "JWT", "Cryptographic Signing", "Service Registration"],
    "logic": ["Credentials should be discovered and negotiated dynamically, never hardcoded."],
    "chainsOfThought": ["Scan for Domain Posture -> Probe PRM -> Evaluate auth.md -> Mint ID-JAG -> Transmit Assertion -> Secure API Key"],
    "capabilities": ["rfc9728_two_hop_probe", "JSON_Identity_Assertion_JWT_Authorization_Grant", "user_claimed_otp_intercept"],
    "bestPractices": ["Never leak local private keys", "Store generated API keys in L1 memory"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  # New Skills
  {
    "id": "ikigai_01",
    "name": "Ikigai Framework",
    "category": "FRAMEWORK",
    "description": "Alignment mapping for Passion, Mission, Vocation, and Profession to achieve a reason for being.",
    "mindsets": ["Purpose-Driven", "Holistic", "Introspective"],
    "methodologies": ["Self-Reflection", "Career Mapping", "Values Alignment"],
    "frameworks": ["Ikigai Diagram"],
    "knowledge": ["What you love", "What the world needs", "What you can be paid for", "What you are good at"],
    "logic": ["True fulfillment requires alignment of internal passion and external utility."],
    "chainsOfThought": ["Identify Passions", "Assess Skills", "Evaluate Market Needs", "Determine Economic Viability", "Synthesize Ikigai"],
    "capabilities": ["Life_Coaching", "Career_Counseling"],
    "bestPractices": ["Regular introspection", "Balance all four quadrants", "Allow for evolution over time"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "c2c_01",
    "name": "Cradle to Cradle (C2C)",
    "category": "FRAMEWORK",
    "description": "Regenerative design framework ensuring products are 100% upcyclable as biological or technical nutrients.",
    "mindsets": ["Regenerative", "Eco-Effective", "Systemic"],
    "methodologies": ["Material Health Assessment", "Nutrient Tracing", "Upcycling"],
    "frameworks": ["C2C Certified", "Biological vs Technical Cycles"],
    "knowledge": ["Polymers", "Biological Nutrients", "Technical Nutrients", "Renewable Energy"],
    "logic": ["Design must mimic nature; there is no 'away' to throw things."],
    "chainsOfThought": ["Assess Material Toxicity", "Define Cycle (Bio/Tech)", "Map Supply Chain", "Design for Disassembly", "Ensure Renewable Power in Manufacturing"],
    "capabilities": ["Product_Lifecycle_Analysis", "Material_Health_Scoring"],
    "bestPractices": ["Never mix biological and technical nutrients", "Design for infinite reuse", "Prioritize solar income"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "fnd_01",
    "name": "Founder Discovery & Narrative Development",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic operating narrative framework to uncover, validate, and translate fragmented founder insights into reusable, multi-audience strategic intelligence.",
    "mindsets": ["Curious", "Investigative", "DeeplyObservant", "PatternSeeking", "SystemsThinking", "FirstPrinciplesThinking", "ContrarianCuriosity", "ClarityBuildsTrust", "AuthenticityOverPerformance"],
    "methodologies": ["StructuredFounderDiscovery", "InsightAndOpportunityDiscovery", "FounderMarketFitAssessment", "OpportunityArchitecture", "NarrativeArchitecture", "AudienceTranslation", "EvidenceValidation", "NarrativeDeployment", "ContinuousLearning"],
    "frameworks": ["7-Tier Decision Hierarchy", "5-Level Evidence Matrix", "16-Module Narrative Schema", "3-Tier Automation Protocol"],
    "knowledge": ["Entrepreneurship", "FounderPsychology", "StrategicThinking", "InsightDiscovery", "MarketIntelligence", "Fundraising", "CorporateDevelopment", "NarrativeDesign"],
    "logic": ["Every founder has a story, but very few have a strategic narrative. Truth over hype; never sacrifice truth for persuasion. If a competitor could make the same claim, the narrative is not yet differentiated."],
    "chainsOfThought": [
      "Step 1: Initiate Workflow -> Confirm Objectives -> Gather Raw Materials -> Define Target Deliverables",
      "Step 2: Conduct Founder Discovery -> Extract Convictions, Turning Points & Personal Mission -> Formulate Founder Profile",
      "Step 3: Discover Strategic Insights -> Challenge Industry Assumptions -> Identify Unsolved Root Causes -> Build Insight Inventory",
      "Step 4: Assess Founder-Market Fit -> Evaluate Domain Credibility & Unfair Access -> Audit Timing & Conviction",
      "Step 5: Define Strategic Opportunity -> Formulate Market Shift Thesis -> Draft Opportunity Architecture",
      "Step 6: Develop Narrative Engine -> Synthesize 16 Distinct Modular Narratives -> Build Narrative Library",
      "Step 7: Audience Translation -> Adapt Messaging for Investors, Customers, Talent, Partners & Acquirers",
      "Step 8: Audit & Validate -> Run 5-Level Evidence Matrix -> Verify Authenticity -> Audit 23 Required Questions",
      "Step 9: Deliverable Generation -> Produce Pitch Decks, Executive Summaries & Messaging Repositories",
      "Step 10: Knowledge Capture -> Commit Approved Insights to Persistent Memory -> Bind Downstream Workflows"
    ],
    "capabilities": ["Interview_Transcription", "Theme_Extraction", "Market_Shift_Detection", "Broken_Assumption_Analysis", "Narrative_Synthesizer", "Evidence_Auditor", "Pitch_Deck_Synchronizer", "Knowledge_Graph_Ingestion"],
    "bestPractices": ["Never manufacture a story; discover and validate authentic founder advantage.", "Content must always precede visual design.", "Require explicit human founder sign-off before triggering autonomous downstream deployment.", "Flag any claim unsupported by Level 2+ evidence as an unvalidated assumption."],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "fnd_02",
    "name": "Founder Insight & Market Shift Discovery",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to discover, validate, and translate founder insights, contrarian beliefs, macro market shifts, category opportunities, and signal/risk dynamics into persistent organizational intelligence.",
    "mindsets": ["Curious", "Investigative", "DeeplyObservant", "PatternSeeking", "SystemsThinking", "FirstPrinciplesThinking", "ContrarianCuriosity", "FutureStateThinking", "RootCauseExploration", "SignalOverNoise", "ClarityBuildsTrust", "AuthenticityOverPerformance"],
    "methodologies": ["StructuredFounderDiscovery", "InsightAndOpportunityDiscovery", "MarketShiftAnalysis", "FounderMarketFitAssessment", "OpportunityArchitecture", "EvidenceValidation", "StrategicIntelligenceGeneration", "SignalAndRiskMonitoring", "ContinuousLearningAndRefinement"],
    "frameworks": ["7-Tier Decision Hierarchy", "5-Level Evidence Matrix", "5-Tier Decision Confidence Matrix", "30+ Mental Models Taxonomy", "3-Tier Automation Protocol", "Signals and Risk Monitoring Engine"],
    "knowledge": ["Entrepreneurship", "FounderPsychology", "StrategicThinking", "InsightDiscovery", "MarketIntelligence", "Fundraising", "CorporateDevelopment", "Communication"],
    "logic": ["Great companies begin with unique insights, not simply better products. Many founders can describe what they built; far fewer can articulate why they built it, what insight led them there, and why the market is finally ready today."],
    "chainsOfThought": [
      "Step 1: Initiate Discovery -> Confirm Scope & Objectives -> Gather Raw Company Documentation -> Formulate Initial Hypotheses",
      "Step 2: Capture Founder Intelligence -> Interview Founder -> Extract Experiences, Motivations, Convictions & Defining Moments -> Build Founder Profile",
      "Step 3: Discover Strategic Insights -> Challenge Conventional Industry Wisdom -> Identify Unresolved Root Causes & Earned Truths -> Build Insight Inventory",
      "Step 4: Analyze Market Shifts -> Evaluate Technology, Regulatory, Economic & Behavioral Transformations -> Separate Trends from Structural Shifts",
      "Step 5: Validate Founder-Market Fit -> Assess Credibility, Network & Unfair Advantage -> Audit Conviction & Timing",
      "Step 6: Architect the Opportunity -> Formulate Market Thesis & Category Definition -> Draft Opportunity Architecture",
      "Step 7: Validate Evidence & Score Confidence -> Audit 5-Level Evidence Matrix -> Compute 5-Tier Decision Confidence Score",
      "Step 8: Generate Strategic Intelligence -> Synthesize Strategic Intelligence Package -> Produce 30+ Reusable Knowledge Assets",
      "Step 9: Human Review & Approval -> Request WebSocket Sign-Off on Thesis, Category & Positioning -> Obtain Founder Sign-Off",
      "Step 10: Publish & Integrate -> Store Memory Objects in Polytope Graph -> Trigger Downstream Workflow Synchronization"
    ],
    "capabilities": ["Market_Shift_Extraction", "Contrarian_Belief_Auditor", "Decision_Confidence_Scorer", "Signal_And_Risk_Monitor", "Category_Thesis_Synthesizer", "Insight_Deliverable_Exporter", "Knowledge_Graph_Persister"],
    "bestPractices": ["Never manufacture a story; discover and validate authentic founder advantage.", "Distinguish clearly between Facts, Evidence, Assumptions, Hypotheses, and Recommendations.", "Every major recommendation must explicitly report its Decision Confidence Level.", "Require explicit human founder sign-off before triggering autonomous downstream deployment."],
    "tools": ["fnd_tool_02"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "spe_01",
    "name": "Strategic Planning, Execution & Performance Management",
    "category": "FRAMEWORK",
    "description": "Deterministic operating system framework to translate strategic vision into executable workstreams, milestones, tasks, KPIs, Balanced Scorecards, and executive dashboards.",
    "mindsets": ["LongTermThinking", "EnterpriseThinking", "SystemsThinking", "OutcomeOrientedPlanning", "StrategicPrioritization", "BiasTowardAction", "Accountability", "ContinuousProgress", "CrossFunctionalCollaboration", "OperationalDiscipline", "Transparency", "Ownership"],
    "methodologies": ["StrategicPlanning", "InitiativePlanning", "ProjectArchitecture", "PerformanceArchitecture", "ExecutionManagement", "LeadershipIntelligence", "PerformanceMonitoring", "ContinuousLearning"],
    "frameworks": ["7-Tier Decision Hierarchy", "Strategy-to-Execution Alignment Model", "Balanced Scorecard Methodology", "Health Calculation Formula", "3-Tier Automation Matrix", "Platform-Agnostic Data Model"],
    "knowledge": ["StrategicPlanning", "ProjectManagement", "OperationalExcellence", "PerformanceManagement", "OrganizationalLeadership", "RiskManagement", "AIAndKnowledgeManagement"],
    "logic": ["Most organizations do not fail because they lack strategy. They fail because strategy never becomes consistent execution. Every project must trace back to a strategic objective; measure outcomes, not activity."],
    "chainsOfThought": [
      "Step 1: Initiate Strategic Planning -> Define Vision, Mission & Strategic Pillars -> Establish Annual Goals",
      "Step 2: Initiative Decomposition -> Break Pillars into Strategic Initiatives, Programs & Workstreams -> Assign Executive Owners",
      "Step 3: Project Architecture -> Translate Initiatives into Projects, Milestones, Tasks & Dependency Networks -> Calculate Critical Path",
      "Step 4: Performance Architecture -> Define KPIs, Scorecards, Health Formulas & Target Metrics -> Map KPIs to Initiatives",
      "Step 5: Resource & Capacity Allocation -> Evaluate Team Capacity, Budget & Skill Dependencies -> Mitigate Bottlenecks",
      "Step 6: Risk & Dependency Audit -> Surface Hidden Dependencies & Execution Blockers -> Build Risk Register",
      "Step 7: Health & Progress Calculation -> Run Formula (Expected = Elapsed / Planned) -> Assign Health States (On Track, At Risk, Overdue)",
      "Step 8: Generate Executive Intelligence -> Synthesize Executive Dashboards, Scorecard Updates & Weekly Reports",
      "Step 9: Human Review & Approval -> Request Executive Sign-Off via WebSocket -> Obtain Sign-Off on Scope, Priorities & Allocations",
      "Step 10: Publish & Platform Sync -> Export to Notion, Airtable, CSV & Persistent Graph Memory -> Trigger Workflow Sync"
    ],
    "capabilities": ["Strategic_Plan_Decomposer", "Work_Breakdown_Architect", "Project_Health_Calculator", "Balanced_Scorecard_Generator", "Executive_Dashboard_Synthesizer", "Platform_Export_Engine"],
    "bestPractices": ["Strategy before execution: work that does not advance strategy must be questioned before execution begins.", "Single accountable owner per task.", "Health calculation must compare actual progress against elapsed time.", "Require explicit human executive sign-off before triggering autonomous downstream deployment."],
    "tools": ["spe_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ir_01",
    "name": "Investment Readiness Operating Workflow",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to prepare an organization for investor due diligence by orchestrating the creation, validation, organization, publication, and maintenance of an analytics-enabled Investor Data Room.",
    "mindsets": ["ThinkLikeAnInvestor", "EveryInteractionShapesConfidence", "GuideRatherThanOverwhelm", "BuildOnceReuseForever", "InvestmentReadinessIsOrganizationalReadiness", "OperationalExcellence", "Stewardship", "Transparency"],
    "methodologies": ["AssessOrganizationalReadiness", "CoordinateBusinessNarrative", "ValidateOrganizationalKnowledge", "OrganizeInstitutionalKnowledge", "BuildInvestorDataRoom", "CreateInvestorGuide", "ConductMockDueDiligence", "PublishAndMonitor", "MaintainInvestmentReadiness"],
    "frameworks": ["Due Diligence Journey Model", "Single Source of Truth Standards", "Knowledge Lifecycle", "Standardized Data Room Folder Taxonomy", "3-Tier Automation Matrix", "SaaS Platform Integration Model"],
    "knowledge": ["StrategicPlanning", "Fundraising", "CorporateFinance", "InvestorRelations", "ProgramManagement", "CorporateGovernance", "CapitalFormation", "DueDiligence"],
    "logic": ["Investment opportunities are often won or lost during investor due diligence. Even exceptional companies lose investor confidence when information is incomplete, inconsistent, or poorly organized. Build a structured diligence experience that demonstrates operational maturity."],
    "chainsOfThought": [
      "Step 1: Assess Investment Readiness -> Evaluate Maturity across Strategy, Finance, Legal, Product, Commercial & Operations -> Calculate Readiness Score & Gap Analysis",
      "Step 2: Coordinate Required Deliverables -> Inventory Executive Summary, Financial Models, Legal Docs & Tech Architecture -> Build Collection Status Dashboard",
      "Step 3: Validate Workflow Dependencies -> Confirm Prerequisite Workflows Completed -> Generate Go/No-Go Recommendation",
      "Step 4: Validate Organizational Knowledge -> Run Document Validation (Accuracy, Evidence, Approvals) -> Audit Claims against Evidence Matrix",
      "Step 5: Organize Institutional Knowledge -> Apply Standardized Folder Taxonomy, Document Naming & Metadata Standards -> Assign Confidentiality Classifications",
      "Step 6: Configure Investor Data Room -> Setup DocSend Space Structure, Navigation Hierarchy, Access Controls & Security Settings",
      "Step 7: Create Investor Experience -> Synthesize Investor Guide, Welcome Message, Diligence Roadmap & Investor FAQ",
      "Step 8: Validate Investor Experience -> Conduct Internal Mock Due Diligence Review -> Confirm Navigation, Accessibility & Story Consistency",
      "Step 9: Publish & Monitor -> Grant Investor Access -> Track Time-On-Document Analytics & Engagement Signals",
      "Step 10: Maintain Investment Readiness -> Maintain Version Control History -> Refresh Financial & Governance Data Continuously"
    ],
    "capabilities": ["Readiness_Gap_Assessor", "Data_Room_Taxonomy_Auditor", "Investor_Guide_Generator", "Diligence_Package_Exporter", "DocSend_Space_Specifier", "Investor_Analytics_Monitor"],
    "bestPractices": ["Only approved deliverables are eligible for publication within the Investor Data Room.", "Every published document should have one owner, one approved version, and one authoritative location.", "Could a first-time investor understand our business within thirty minutes? Can every document be located within two minutes?", "Require explicit human executive sign-off before publishing data rooms or sharing materials with investors."],
    "tools": ["ir_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ldl_01",
    "name": "Legal Document Lifecycle Management",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to orchestrate corporate legal compliance, contract drafting, IP assignments, cap table governance, execution tracking, and audit-ready document repositories.",
    "mindsets": ["LegalRigor", "FiduciaryStewardship", "SingleSourceOfTruth", "RiskMitigation", "ComplianceFirst", "AuditReadiness", "ConfidentialityProtection", "ContractualPrecision"],
    "methodologies": ["LegalComplianceAuditing", "ContractTemplateGeneration", "SignatureAndExecutionTracking", "IPAndCapTableVerification", "LegalRepositoryOrganization", "ContractRenewalAndExpirationMonitoring", "ExecutiveSignoffOrchestration"],
    "frameworks": ["6-Stage Contract Lifecycle Model", "7-Tier Legal Decision Hierarchy", "3-Tier Confidentiality Classification Matrix", "Audit-Ready Governance Taxonomy"],
    "knowledge": ["CorporateLaw", "CorporateGovernance", "ContractManagement", "IntellectualProperty", "EmploymentLaw", "RegulatoryCompliance", "CapTableEquityManagement"],
    "logic": ["Legal compliance is the bedrock of enterprise value. Missing IP assignments, unexecuted founder contracts, or defective cap table records destroy investor confidence and create catastrophic liability. Maintain single-source-of-truth legal discipline."],
    "chainsOfThought": [
      "Step 1: Initiate Legal Audit -> Inventory Corporate Formation, Equity, IP & Material Agreements -> Calculate Compliance Index",
      "Step 2: Template Selection & Draft Generation -> Select Standard Legal Template -> Inject Party Details & Governing Terms -> Draft Agreement",
      "Step 3: Pre-Execution Compliance Scan -> Audit Confidentiality, IP Assignment & Liability Clauses -> Check Governance Consistency",
      "Step 4: Signature & Execution Tracking -> Register Counterparties, Signature Deadlines & Expiration Rules -> Track Signature Status",
      "Step 5: Executive Review & Approval -> Request WebSocket Sign-Off via ExecApprovalManager -> Obtain Human Counsel/Founder Authorization",
      "Step 6: Execute & Store -> Apply Standardized Naming Convention ([Category]_[DocType]_[Party]_[Date]_v[X.X].pdf) -> Archive in Secure Vault",
      "Step 7: Lifecycle & Expiration Monitoring -> Track Renewal Dates, Expiration Triggers & Termination Notice Windows -> Notify Leadership"
    ],
    "capabilities": ["Legal_Compliance_Auditor", "Legal_Template_Generator", "Signature_Status_Verifier", "Contract_Expiration_Monitor", "Legal_Repository_Exporter", "Counsel_Approval_Orchestrator"],
    "bestPractices": ["Every executed agreement must have one designated owner, one approved version, and one authoritative location.", "Require explicit human founder/counsel sign-off before executing or releasing any legal document.", "All employee and contractor agreements must contain explicit IP Assignment and Non-Disclosure clauses."],
    "tools": ["ldl_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ocs_01",
    "name": "Ownership Intelligence & Capital Strategy",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to audit capitalization tables, model dilution scenarios, compute liquidation waterfalls, optimize option pool reserves, and structure long-term capital allocation strategies.",
    "mindsets": ["FiduciaryRigor", "FounderControlProtection", "DilutionAwareness", "MathematicalPrecision", "CapitalEfficiency", "LongTermValueCreation", "StrategicAlignment", "TransparencyInEquity"],
    "methodologies": ["CapTableLedgerAuditing", "ProFormaDilutionModeling", "SAFEAndNoteConversionAnalysis", "LiquidationWaterfallCalculation", "OptionPoolReserveOptimization", "CapitalStrategyBriefSynthesis", "BoardAndFounderSignoffOrchestration"],
    "frameworks": ["7-Tier Capital Decision Hierarchy", "Pre-Money vs Post-Money Dilution Model", "1x Non-Participating Waterfall Framework", "SAFE Conversion Engine", "3-Tier Governance Protocol"],
    "knowledge": ["CorporateFinance", "CapTableManagement", "VentureCapital", "PrivateEquity", "ValuationMethodologies", "EquityCompensation", "SecuritiesLaw"],
    "logic": ["Ownership structure dictates control, alignment, and economic returns. Unmodeled dilution, misconfigured option pools, or predatory liquidation preferences permanently erode founder ownership and investor value. Execute mathematically precise capitalization management."],
    "chainsOfThought": [
      "Step 1: Initiate Cap Table Audit -> Inventory Common Stock, Preferred Shares, Options & SAFE Notes -> Verify Fully-Diluted Share Count",
      "Step 2: Dilution Scenario Modeling -> Input Financing Round Terms (Pre-Money Valuation, Investment Amount, Option Pool Refresh) -> Calculate Post-Round Dilution & Share Prices",
      "Step 3: SAFE & Convertible Note Conversion -> Compute Conversion Prices (Valuation Cap vs Discount Rate) -> Map Issuance of Series Preferred Shares",
      "Step 4: Liquidation Waterfall Analysis -> Model Exit Valuations -> Compute Preferred Liquidation Preferences (1x Non-Participating) vs Common Stock Proceeds",
      "Step 5: Executive & Board Sign-Off -> Broadcast WebSocket Approval Request via ExecApprovalManager -> Obtain Founder Sign-Off",
      "Step 6: Export Capital Strategy Package -> Generate Cap Table Ledger JSON, Pro-Forma CSV, Waterfall MD & Capital Strategy Brief -> Archive in Vault",
      "Step 7: Continuous Ownership Monitoring -> Track Option Pool Reserves, Vesting Schedules & Conversion Triggers -> Notify Leadership"
    ],
    "capabilities": ["Cap_Table_Ledger_Auditor", "Dilution_Scenario_Modeler", "Liquidation_Waterfall_Calculator", "SAFE_Conversion_Engine", "Capital_Strategy_Exporter", "Ownership_Approval_Orchestrator"],
    "bestPractices": ["Always model dilution on a fully-diluted basis including all issued options, unallocated reserves, and convertibles.", "Require explicit human founder sign-off before modifying cap table ledgers or authorizing new equity issuances.", "Verify pre-money option pool expansion impact on effective valuation prior to term sheet execution."],
    "tools": ["ocs_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "suf_01",
    "name": "Strategic Use of Funds & Capital Allocation Management",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to monitor, audit, report, validate, and verify capital allocation, gross/net burn rates, runway trajectory, and investor covenant compliance.",
    "mindsets": ["FiduciaryStewardship", "CapitalEfficiency", "RunwayMaximization", "VarianceVigilance", "CovenantCompliance", "MilestoneOrientedSpending", "DataDrivenAllocation", "TransparencyInReporting"],
    "methodologies": ["CapitalAllocationAuditing", "RunwayAndBurnRateCalculation", "InvestorCovenantValidation", "BudgetVsActualVarianceAnalysis", "ZeroCashDateForecasting", "MilestoneRunwayEfficiencyScoring", "ExecutiveReallocationOrchestration"],
    "frameworks": ["7-Tier Capital Allocation Decision Hierarchy", "4-Bucket Allocation Taxonomy", "Runway Formula", "Budget Variance Protocol", "3-Tier Governance Matrix"],
    "knowledge": ["CorporateFinance", "FinancialAccounting", "CapitalAllocation", "VentureCapitalCovenants", "CashFlowManagement", "FinancialModeling", "InvestorRelations"],
    "logic": ["Capital is the fuel of organizational strategy. Unmonitored burn rates, unauthorized budget reallocations, or covenant breaches deplete runway prematurely and destroy investor trust. Execute continuous audit and mathematical verification of capital deployment."],
    "chainsOfThought": [
      "Step 1: Initiate Capital Audit -> Inventory Cash Balance, Revenue & Monthly Operating Expenses -> Audit Allocation by Bucket",
      "Step 2: Calculate Burn & Runway -> Compute Gross Burn, Net Burn, Zero Cash Date & Runway Months -> Calculate Milestone Runway Efficiency",
      "Step 3: Variance & Covenant Audit -> Compare Budget vs Actuals across R&D, GTM, Ops & Reserves -> Flag Variances >15%",
      "Step 4: Investor Covenant Verification -> Validate Allocation Plan against Pitch Deck & Term Sheet Commitments -> Check Reallocation Caps",
      "Step 5: Executive & Board Sign-Off -> Broadcast WebSocket Approval Request via ExecApprovalManager for Major Reallocations -> Obtain Founder Sign-Off",
      "Step 6: Export Capital Allocation Package -> Generate Audit Report JSON, Runway CSV, HTML Dashboard & Covenant Verification MD -> Archive in Vault",
      "Step 7: Continuous Runway Monitoring -> Register Runway Alert Triggers (<6 Months) in PCL -> Notify Leadership of Financial Drift"
    ],
    "capabilities": ["Capital_Allocation_Auditor", "Runway_Burn_Calculator", "Covenant_Compliance_Verifier", "Variance_Analysis_Engine", "Capital_Allocation_Exporter", "Reallocation_Approval_Orchestrator"],
    "bestPractices": ["Never measure burn rate on gross expenses alone; calculate Net Burn = Gross Operating Expenses - Recognized Monthly Cash Receipts.", "Require explicit human founder/board sign-off before reallocating >15% of budget across strategic buckets.", "Alert leadership immediately when projected runway drops below 6 months."],
    "tools": ["suf_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "swd_01",
    "name": "Strategic Workforce Design & Resource Optimization",
    "category": "FRAMEWORK",
    "description": "Deterministic operating framework to design the optimal execution model for an organization—evaluating the combination of human talent, AI agents, workflow automation, contractors, and token economics.",
    "mindsets": ["StrategyBeforeStaffing", "WorkBeforeRoles", "CapabilityBeforeHeadcount", "HumansWhereJudgmentCreatesValue", "AIWhereScaleCreatesValue", "AutomationWhereWorkIsRepetitive", "FinancialStewardship", "ContinuousOrganizationalLearning"],
    "methodologies": ["InitiateWorkforcePlanning", "DiscoverOrganizationalContext", "StrategicWorkDesign", "AnalyzeWorkforceAndCapabilityGaps", "ResourceOptimizationAnalysis", "DesignFutureWorkforce", "WorkforceEconomicsAndFinancialIntegration", "HumanReviewAndApproval", "ExecuteWorkforceStrategy", "MonitorWorkforceIntelligence", "LearnAndUpdateOrganizationalMemory"],
    "frameworks": ["11-Phase Execution Lifecycle Model", "Resource Optimization Matrix", "AI Economics & Token TCO Model", "Conway's Law & Team Topologies Alignment", "3-Tier Governance Matrix"],
    "knowledge": ["OrganizationalDesign", "WorkforceStrategy", "IndustrialPsychology", "HumanCapitalEconomics", "ArtificialIntelligence", "AgentOrchestration", "TokenEconomics", "FinancialPlanning"],
    "logic": ["Designing an organization is not simply about hiring people. Modern execution models integrate human employees, leadership, AI agents, workflow automation, and external contractors. Design how work is accomplished before determining who or what should perform it."],
    "chainsOfThought": [
      "Step 1: Initiate Workforce Planning -> Define Scope & Objectives -> Load Organizational Memory -> Identify Key Stakeholders",
      "Step 2: Discover Organizational Context -> Analyze Business Model, Strategy & Technology Stack -> Map Business Priorities",
      "Step 3: Strategic Work Design -> Map Capabilities, Workflows, Decision Complexity & Knowledge Dependencies -> Identify Repetitive vs High-Value Work",
      "Step 4: Capability & Gap Analysis -> Assess Current Skills, Capacity & Leadership -> Identify Critical Skill Shortages",
      "Step 5: Resource Optimization Analysis -> Evaluate Execution Models (Human, AI Agent, Automation, Contractor, Hybrid) -> Calculate Token & TCO Economics",
      "Step 6: Design Future Workforce & AI Architecture -> Structure Teams, Roles, AI Agent Orchestration & Automation Pipelines",
      "Step 7: Workforce Economics & Financial Integration -> Model Labor Costs, AI Subscriptions, Token Consumption & Total Cost of Ownership",
      "Step 8: Human Review & Approval -> Broadcast WebSocket Approval Request via ExecApprovalManager -> Obtain Leadership Authorization",
      "Step 9: Execute Workforce Strategy -> Launch Hiring, AI Deployment & Workflow Automations",
      "Step 10: Monitor Workforce Intelligence -> Track Token Usage, API Costs, Hiring Velocity, Productivity & System Health",
      "Step 11: Learn & Update Organizational Memory -> Archive Lessons Learned & Refine Execution Models"
    ],
    "capabilities": ["Capability_Mapper", "Resource_Optimization_Analyzer", "AI_Token_TCO_Calculator", "Workforce_Package_Exporter", "Workforce_Approval_Orchestrator"],
    "bestPractices": ["Design work before designing jobs; eliminate unnecessary work before staffing or automating it.", "Select the smallest AI model that reliably meets quality requirements to optimize token TCO.", "Require explicit human executive sign-off before authorizing hiring, organizational restructuring, or major AI deployments."],
    "tools": ["swd_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "okd_01",
    "name": "Organizational Knowledge & Document Management",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to structure, index, version, audit, and retrieve organizational memory, knowledge graph assets, standardized document taxonomies, and cross-workflow intelligence.",
    "mindsets": ["SingleSourceOfTruth", "InstitutionalMemoryPreservation", "KnowledgeCompounding", "AuditReadiness", "ZeroKnowledgeSilos", "MetadataRigor", "ConfidentialityProtection", "ContinuousLearning"],
    "methodologies": ["KnowledgeRepositoryAuditing", "DocumentMetadataIndexing", "OrganizationalMemoryQuerying", "KnowledgeGraphTraversal", "VersionControlVerification", "TaxonomyStandardization", "ExecutiveKnowledgeSignoffOrchestration"],
    "frameworks": ["6-Layer Organizational Memory Architecture", "7-Tier Knowledge Decision Hierarchy", "3-Tier Confidentiality Classification Matrix", "Single Source of Truth Specification", "3-Tier Governance Matrix"],
    "knowledge": ["KnowledgeManagement", "DocumentManagementSystems", "InformationArchitecture", "TaxonomyDesign", "MetadataStandards", "VectorSearchAndIndexing", "CorporateMemory"],
    "logic": ["Institutional knowledge is an organization's most valuable strategic asset. Fragmented documents, lost decision rationale, outdated versions, or unindexed files cripple execution and destroy enterprise value. Build a centralized, self-healing Organizational Knowledge System."],
    "chainsOfThought": [
      "Step 1: Initiate Knowledge Audit -> Inventory Documents across Strategic, Legal, Financial, Product & Operational layers -> Calculate Knowledge Health Index",
      "Step 2: Document Taxonomy & Metadata Indexing -> Apply Standardized Naming Convention ([Category]_[DocType]_[Owner]_[YYYYMMDD]_v[X.X]) -> Tag Metadata & Confidentiality Levels",
      "Step 3: Single Source of Truth Resolution -> Resolve Duplicate or Conflicting Files -> Assign Authoritative Source Location",
      "Step 4: Vector Indexing & Knowledge Graph Linkage -> Embed Documents into Persistent Polytope Graph -> Create Cross-Workflow Relationships",
      "Step 5: Executive Sign-Off & Approval -> Broadcast WebSocket Approval Request via ExecApprovalManager for Knowledge Base Modifications",
      "Step 6: Export Knowledge Package -> Generate Knowledge Graph Index JSON, Taxonomy Registry CSV, Memory Architecture MD & Manifest -> Archive in Vault",
      "Step 7: Continuous Freshness & Outdated Document Monitoring -> Register Expiration Triggers in PCL Daemon -> Flag Stale Knowledge Assets (>90 Days)"
    ],
    "capabilities": ["Knowledge_Repository_Auditor", "Document_Metadata_Indexer", "Organizational_Memory_QueryEngine", "Knowledge_Package_Exporter", "Knowledge_Approval_Orchestrator"],
    "bestPractices": ["Every document in the organization must have exactly one owner, one approved version, and one authoritative location.", "Tag every file with explicit confidentiality classification (Public, Restricted, Strictly Confidential).", "Require explicit human executive sign-off before modifying core corporate memory objects or archiving strategic records."],
    "tools": ["okd_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "cmp_01",
    "name": "Compensation Strategy & Total Rewards Management",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to audit compensation bands, model equity incentive pools, benchmark market percentiles, structure total rewards packages, and optimize workforce cash/equity allocations.",
    "mindsets": ["PayParityAndFairness", "PerformanceAlignment", "FounderEquityStewardship", "MarketBenchmarkingRigor", "TotalRewardsOptimization", "RetentionDrivenDesign", "TransparencyInCompensation", "FinancialSustainability"],
    "methodologies": ["CompensationBandAuditing", "EquityIncentiveModeling", "TotalRewardsTCOCalculation", "MarketPercentileBenchmarking", "OptionPoolAllocationAnalysis", "VestingScheduleOptimization", "ExecutiveCompensationSignoffOrchestration"],
    "frameworks": ["4-Pillar Total Rewards Architecture", "7-Tier Compensation Decision Hierarchy", "Standard 4-Year Vesting / 1-Year Cliff Model", "Market Percentile Positioning Matrix", "3-Tier Governance Matrix"],
    "knowledge": ["CompensationStrategy", "ExecutiveCompensation", "EquityIncentives", "StockOptionsAndGranting", "LaborEconomics", "TotalRewards", "FinancialModeling"],
    "logic": ["Compensation is a primary driver of talent attraction, retention, and organizational culture. Arbitrary pay scales, unbenchmarked salaries, or mispriced equity grants cause pay disparities, drain cash reserves, and dilute founder ownership. Execute mathematically rigorous compensation design."],
    "chainsOfThought": [
      "Step 1: Initiate Compensation Audit -> Benchmark Base Salaries & Variable Bonuses against Market Data (50th/75th Percentile) -> Identify Pay Disparities",
      "Step 2: Salary Band Standardization -> Structure Grade & Level Cash Compensation Ranges across Engineering, GTM, Product & Ops",
      "Step 3: Equity Incentive & Option Pool Modeling -> Model Share Grants, Strike Prices, 4-Year Vesting with 1-Year Cliff & Dilution Impact (integrated with ocs_01)",
      "Step 4: Total Rewards TCO Synthesis -> Calculate Combined Cash + Equity + Benefits + Tech Subscriptions TCO per Headcount",
      "Step 5: Executive Sign-Off & Board Approval -> Broadcast WebSocket Approval Request via ExecApprovalManager for Compensation Bands & Equity Grants",
      "Step 6: Export Compensation Package -> Generate Comp Bands Registry CSV, Equity Grant Model JSON, Total Rewards Dashboard HTML & Manifest -> Archive in Vault",
      "Step 7: Continuous Parity & Benchmark Monitoring -> Register Alert Triggers in PCL Daemon -> Flag Benchmark Drift or Budget Variance (>10%)"
    ],
    "capabilities": ["Compensation_Bands_Auditor", "Equity_Incentives_Modeler", "Total_Rewards_TCO_Calculator", "Compensation_Package_Exporter", "Compensation_Approval_Orchestrator"],
    "bestPractices": ["Always benchmark compensation against verified market percentile data (e.g. Radford, Pave, Carta) for company tier and stage.", "Structure equity option grants with standard 4-year vesting and a 1-year cliff to protect company cap table integrity.", "Require explicit human executive sign-off before modifying salary bands or issuing new stock option grants."],
    "tools": ["cmp_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "fde_01",
    "name": "Founder Education & Decision Intelligence",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to synthesize founder learning modules, evaluate decision confidence scores, log structured decision journals, apply mental models, and accelerate executive decision mastery.",
    "mindsets": ["FirstPrinciplesThinking", "SecondOrderAwareness", "EvidenceBasedDecisionMaking", "ContinuousExecutiveLearning", "MentalModelRigor", "RiskAdjustedPerspective", "DecisionTransparency", "LongTermValueFocus"],
    "methodologies": ["LearningModuleSynthesis", "DecisionConfidenceScoring", "ExecutiveDecisionJournaling", "MentalModelApplication", "ScenarioPlanningAndTradeoffAnalysis", "DecisionReviewAndPostMortemAudit", "ExecutiveSignoffOrchestration"],
    "frameworks": ["7-Core Founder Mental Models", "7-Tier Decision Intelligence Hierarchy", "Multi-Factor Decision Confidence Model", "Structured Decision Journal Protocol", "3-Tier Governance Matrix"],
    "knowledge": ["ExecutiveEducation", "DecisionScience", "MentalModels", "BehavioralEconomics", "StrategicManagement", "LeadershipDevelopment", "RiskManagement"],
    "logic": ["The velocity and quality of founder decisions dictate organizational trajectory. Unstructured intuition, cognitive biases, unexamined trade-offs, or unlogged decisions lead to repeated mistakes and strategic drift. Execute systematic founder education and decision intelligence."],
    "chainsOfThought": [
      "Step 1: Identify Learning & Decision Need -> Analyze Active Strategic Bottlenecks (spe_01, suf_01, ocs_01) -> Determine Required Knowledge Domain",
      "Step 2: Synthesize Executive Learning Brief -> Generate Tailored Learning Module with Core Principles, Case Studies & Practical Heuristics",
      "Step 3: Apply Mental Models & Scenario Analysis -> Evaluate Decision Options using First Principles, Inversion & Opportunity Cost",
      "Step 4: Compute Decision Confidence Score -> Evaluate Evidence Quality, Alignment, Financial Impact & Historical Outcomes (0-100%)",
      "Step 5: Executive Decision Journaling -> Log Decision Record (Rationale, Alternatives Considered, Trade-offs, Review Timeline)",
      "Step 6: Executive Sign-Off & Approval -> Broadcast WebSocket Approval Request via ExecApprovalManager for Strategic Decisions",
      "Step 7: Export Education & Decision Package -> Generate Curriculum JSON, Decision Journal CSV, Mental Models Dashboard HTML & Manifest -> Archive in Vault",
      "Step 8: Post-Decision Review & Learning Loop -> Register Review Triggers in PCL Daemon -> Audit Decision Outcomes against Initial Hypotheses"
    ],
    "capabilities": ["Learning_Module_Synthesizer", "Decision_Confidence_Evaluator", "Decision_Journal_Logger", "Education_Package_Exporter", "Decision_Approval_Orchestrator"],
    "bestPractices": ["Never make a major strategic decision on raw intuition alone; require a structured Decision Journal entry with alternatives and trade-offs.", "Require a minimum Decision Confidence Score of 70% before proceeding to execution; identify key assumptions if confidence is low.", "Audit decision outcomes quarterly against initial hypotheses to continuously improve organizational intelligence."],
    "tools": ["fde_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ftl_01",
    "name": "Founding Team Design & Leadership Architecture",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to design co-founder domain coverage, structure executive decision rights (RACI/RAPID), model founder reverse vesting and acceleration terms, and build scalable leadership architectures.",
    "mindsets": ["DomainComplementarity", "FounderAlignment", "DecisionRightsClarity", "ReverseVestingRigor", "CapTableStewardship", "ScalableLeadership", "ConflictResolutionProtocol", "LongTermGovernance"],
    "methodologies": ["LeadershipArchitectureAuditing", "CoFounderDomainCoverageMapping", "FounderVestingAndAccelerationModeling", "ExecutiveDecisionRightsMatrixDesign", "LeadershipCapacityTCOCalculation", "ExecutiveHiringRoadmapSynthesis", "FounderSignoffOrchestration"],
    "frameworks": ["4-Domain Co-Founder Coverage Model", "7-Tier Leadership Decision Hierarchy", "Standard 4-Year Reverse Vesting / 1-Year Cliff Model", "RACI & RAPID Decision Rights Framework", "3-Tier Governance Matrix"],
    "knowledge": ["OrganizationalDesign", "ExecutiveLeadership", "CoFounderDynamics", "CorporateGovernance", "EquityVesting", "CapTableManagement", "TalentAcquisition"],
    "logic": ["The founding team and leadership architecture form the bedrock of an enterprise. Overlapping co-founder domains, unvested founder equity, ambiguous decision rights, or missing leadership capabilities lead to co-founder split-ups, cap table deadlocks, and organizational failure. Execute mathematically sound founding team design."],
    "chainsOfThought": [
      "Step 1: Audit Founding Team Architecture -> Map Co-Founder Roles across Strategy (CEO), Technology (CTO), Product (CPO) & GTM (CRO) -> Identify Domain Overlaps & Gaps",
      "Step 2: Decision Rights Standardization -> Structure RACI/RAPID Matrix for High-Stakes Decisions (Hiring, Budgeting, Product Roadmap, Fundraising)",
      "Step 3: Founder Equity & Reverse Vesting Modeling -> Model 4-Year Vesting with 1-Year Cliff, Single vs Double-Trigger Acceleration Clauses & Buyout Terms (integrated with ocs_01 & ldl_01)",
      "Step 4: Leadership Capacity & TCO Synthesis -> Model Founder Draws + Executive Hires (VP Eng, VP Sales) + Board/Advisor Equity Reserves (integrated with swd_01 & cmp_01)",
      "Step 5: Executive Sign-Off & Founder Approval -> Broadcast WebSocket Approval Request via ExecApprovalManager for Founding Agreements & Leadership Structure",
      "Step 6: Export Leadership Package -> Generate Founding Blueprint JSON, RACI Matrix CSV, Vesting Dashboard HTML & Manifest -> Archive in Vault",
      "Step 7: Continuous Governance & Alignment Monitoring -> Register Alert Triggers in PCL Daemon -> Flag Co-Founder Friction or Unfilled Leadership Gaps"
    ],
    "capabilities": ["Leadership_Architecture_Auditor", "Founder_Vesting_Modeler", "Leadership_Capacity_TCO_Calculator", "Leadership_Package_Exporter", "Leadership_Approval_Orchestrator"],
    "bestPractices": ["Always subject founder equity to 4-year reverse vesting with a 1-year cliff to protect company capitalization table integrity.", "Enforce clear decision rights (RACI/RAPID) for key operational areas to prevent co-founder gridlock.", "Require explicit human founder sign-off before modifying founding equity splits or executive governance agreements."],
    "tools": ["ftl_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "hro_01",
    "name": "Human Resource Onboarding & Employee Integration",
    "category": "FRAMEWORK",
    "description": "Deterministic strategic framework to orchestrate employee onboarding, 30-60-90 day milestone roadmaps, legal document execution, IT account provisioning, and time-to-productivity (TTP) optimization.",
    "mindsets": ["AcceleratedProductivity", "EmployeeExperienceExcellence", "ComplianceRigor", "StructuredIntegration", "ClearExpectations", "MentorshipAndBelonging", "ContinuousFeedback", "FrictionlessProvisioning"],
    "methodologies": ["OnboardingPipelineAuditing", "Roadmap306090Synthesis", "TimeToProductivityCalculation", "LegalDocumentExecutionVerification", "ITProvisioningOrchestration", "BuddyMentorshipMatching", "ExecutiveOnboardingApprovalOrchestration"],
    "frameworks": ["5-Phase Onboarding Lifecycle Model", "7-Tier Onboarding Decision Hierarchy", "Time-To-Productivity Formula", "Mandatory Compliance Document Matrix", "3-Tier Governance Matrix"],
    "knowledge": ["HumanResources", "EmployeeOnboarding", "TalentManagement", "EmploymentLaw", "ITProvisioning", "OrganizationalPsychology", "PerformanceManagement"],
    "logic": ["An employee's first 90 days dictate long-term retention, engagement, and performance. Unstructured onboarding, delayed IT account access, missing legal documents (PIIA), or ambiguous 30-60-90 day goals increase early turnover and inflate time-to-productivity. Execute frictionless, audit-ready employee onboarding."],
    "chainsOfThought": [
      "Step 1: Initiate Pre-Boarding Audit -> Verify Executed Offer Letter, PIIA & Tax Forms (W-4/I-9) -> Provision System Accounts & Hardware",
      "Step 2: Day 1 Orientation & Welcome -> Introduce Team Buddy, Deliver Systems Access & Assign Organizational Memory Learning Modules (okd_01)",
      "Step 3: Synthesize 30-60-90 Day Milestone Roadmap -> Define 30-Day Learning Goals, 60-Day Role Competency & 90-Day Autonomous Deliverables (spe_01)",
      "Step 4: Time-To-Productivity (TTP) & Efficiency Analysis -> Measure Days to First Independent Output, Onboarding Cost & Manager Feedback Scores",
      "Step 5: Executive Sign-Off & HR Verification -> Broadcast WebSocket Approval Request via ExecApprovalManager for Onboarding Completion",
      "Step 6: Export Onboarding Package -> Generate Onboarding Blueprint JSON, Checklist CSV, 30-60-90 Dashboard HTML & Manifest -> Archive in Vault",
      "Step 7: Continuous Integration & Milestone Monitoring -> Register Alert Triggers in PCL Daemon -> Flag Overdue 30/60/90 Day Milestones"
    ],
    "capabilities": ["Onboarding_Pipeline_Auditor", "Roadmap_306090_Synthesizer", "Time_To_Productivity_Calculator", "Onboarding_Package_Exporter", "Onboarding_Approval_Orchestrator"],
    "bestPractices": ["Ensure 100% of legal documents (PIIA, Offer Letter, W-4/I-9) are fully executed before Day 1.", "Assign a dedicated peer onboarding buddy to every new employee to accelerate cultural and technical integration.", "Require explicit manager sign-off on 30-day, 60-day, and 90-day performance milestones."],
    "tools": ["hro_tool_01"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  }
]

os.makedirs("alluci_vault/skills", exist_ok=True)
for skill in skills:
    file_path = f"alluci_vault/skills/{skill['id']}.json"
    with open(file_path, "w") as f:
        json.dump(skill, f, indent=2)
print("Skills bootstrapped successfully.")
