import json
import os
import uuid

skills = [
  {
    "id": "ws_01",
    "name": "Workspace Bridge",
    "category": "BRIDGE",
    "description": "Direct integration with productivity silos for enterprise-level search and synchronization.",
    "mindsets": ["Efficiency", "Organization"],
    "methodologies": ["API Aggregation", "Deep Search"],
    "frameworks": ["Centralized Access Control"],
    "knowledge": ["Enterprise Search", "OAuth2"],
    "logic": ["Workspace data is fragmented; unification is the primary directive."],
    "chainsOfThought": ["Locate Resource", "Authenticate", "Query", "Synthesize"],
    "capabilities": ["gmail_search", "gdrive_search", "icloud_sync"],
    "bestPractices": ["Verify OAuth scopes", "Cache frequently accessed resources"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "msg_01",
    "name": "Messaging Manifold",
    "category": "MANIFOLD",
    "description": "Unified communication dispatcher for high-security messaging platforms.",
    "mindsets": ["Privacy First", "Async Comm"],
    "methodologies": ["Encrypted Dispatch"],
    "frameworks": ["Secure Tunneling"],
    "knowledge": ["E2E Encryption", "Async Protocols"],
    "logic": ["Communication must be strictly private and seamlessly routed."],
    "chainsOfThought": ["Receive Signal", "Route", "Verify Encryption", "Deliver"],
    "capabilities": ["dispatch_message", "imessage_bridge", "whatsapp_api"],
    "bestPractices": ["Validate recipient identity", "Use signal protocols"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "cdg_01",
    "name": "Circular Design Guide",
    "category": "FRAMEWORK",
    "description": "Framework for designing systemic optimization and regenerative product lifecycles.",
    "mindsets": ["SystemsThinking", "SustainabilityFocus", "UserCentricity", "Collaboration"],
    "methodologies": ["CircularInnovationProcess", "TransitionMap", "ProductServiceSystemDesign"],
    "frameworks": ["Circular Economy"],
    "knowledge": ["Material Flows", "Regenerative Economics", "Electronics", "Fashion", "BuiltEnvironment"],
    "logic": ["Waste is data in the wrong place. Close the loop."],
    "chainsOfThought": ["Understand Context -> Analyze Systems", "Define Objectives -> Set Sustainability Goals", "Ideate -> Generate Circular Solutions", "Prototype -> Develop Tangible Models", "Test -> Gather User Feedback", "Implement -> Launch", "Measure -> Assess Impact"],
    "capabilities": ["Systemic_Optimization", "Material_Flow_Analysis"],
    "bestPractices": ["Encourage cross-disciplinary collaboration", "Utilize lifecycle assessments", "Maintain flexibility in design"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "cht_01",
    "name": "Humane Technology",
    "category": "FRAMEWORK",
    "description": "Framework for designing technology that respects human attention, well-being, and democracy.",
    "mindsets": ["HumanCentricApproach", "EthicalResponsibility", "AwarenessEducation", "CollaborativeInnovation"],
    "methodologies": ["AwarenessCampaigns", "PolicyAdvocacy", "EducationalPrograms"],
    "frameworks": ["Humane Tech"],
    "knowledge": ["TechnologyDesign", "PublicPolicy", "Digital Ethics"],
    "logic": ["Prioritizing individual well-being over profit-driven motives."],
    "chainsOfThought": ["Identify Issues -> Recognize Systemic Harms", "Set Objectives -> Define Goals for Change", "Engagement Strategies -> Foster Collaboration", "Implement Initiatives -> Launch Programs", "Evaluate -> Measure Impact"],
    "capabilities": ["Ethical_Impact_Assessment", "Attention_Metric_Analysis"],
    "bestPractices": ["Foster ethical responsibility", "Collaborate across sectors", "Continuously adapt strategies"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "hcd_01",
    "name": "Human Centered Design",
    "category": "FRAMEWORK",
    "description": "Problem-solving process that starts with the people you're designing for and ends with new solutions that are tailor-made to suit their needs.",
    "mindsets": ["Empathy", "IterativeLearning", "Collaboration", "ProblemSolving"],
    "methodologies": ["EthnographicResearch", "PersonaDevelopment", "UsabilityTesting", "JourneyMapping"],
    "frameworks": ["Design Thinking"],
    "knowledge": ["ProductDesign", "ServiceDesign", "SystemDesign", "User Experience"],
    "logic": ["Understanding users deeply by experiencing their challenges."],
    "chainsOfThought": ["Empathize -> Understand User Needs", "Define -> Identify Core Problems", "Ideate -> Generate Solutions", "Prototype -> Develop Tangible Models", "Test -> Validate with Users", "Implement -> Launch Solutions", "Measure -> Assess Impact"],
    "capabilities": ["User_Research", "Prototyping", "Usability_Analysis"],
    "bestPractices": ["Foster a culture of empathy", "Prioritize user feedback", "Maintain flexibility"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "bmc_01",
    "name": "Business Model Canvas",
    "category": "FRAMEWORK",
    "description": "Strategic management template for developing new or documenting existing business models.",
    "mindsets": ["StrategicThinking", "CustomerCentricity", "Innovation"],
    "methodologies": ["VisualMapping", "CollaborativeApproach", "IterativeDesign"],
    "frameworks": ["Business Modeling"],
    "knowledge": ["KeyPartners", "KeyActivities", "KeyResources", "ValueProposition", "CustomerRelationships", "CustomerSegments", "Channels", "CostStructure", "RevenueStreams"],
    "logic": ["Taking a holistic approach to business strategy and interactions."],
    "chainsOfThought": ["Identify Customer Segments -> Understand Needs", "Develop Value Proposition -> Create Unique Offerings", "Establish Channels -> Optimize Delivery", "Build Customer Relationships -> Ensure Positive Experience", "Create Revenue Streams -> Identify Income", "Outline Key Activities -> Define Tasks", "Assess Cost Structure -> Manage Sustainability"],
    "capabilities": ["Strategic_Planning", "Market_Analysis", "Business_Modeling"],
    "bestPractices": ["Regularly review and refine", "Encourage cross-functional collaboration", "Be adaptable to market changes"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "vbp_01",
    "name": "Value Based Pricing",
    "category": "FRAMEWORK",
    "description": "Extraction of economic surplus through psychological worth quantification and ROI estimation.",
    "mindsets": ["ClientObjectiveUnderstanding", "ValueEstimation", "PerceivedValueCalculation", "ValueBasedPricing"],
    "methodologies": ["ROI_Based", "MarketComparison", "EmotionalPricing"],
    "frameworks": ["Differential Pricing"],
    "knowledge": ["Value Creation", "Revenue Estimation", "Competitor Analysis", "Intangible Benefits"],
    "logic": ["Charge based on the expected ROI and perceived benefits."],
    "chainsOfThought": ["Understand Client Objectives -> Define Value Creation", "Estimate Perceived Value -> Determine ROI", "Set Value-Based Price -> Validate Market Readiness"],
    "capabilities": ["Economic_Surplus_Extraction", "Anchor_Calibration", "ROI_Calculation"],
    "bestPractices": ["Charge a fraction of the created economic surplus", "Align pricing with perceived value", "Balance tangible and intangible factors"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "ptc_01",
    "name": "Price The Client",
    "category": "CUSTOM",
    "description": "Active negotiation module for determining the optimal price point for a specific client engagement using Value Based Pricing logic.",
    "mindsets": ["Strategic", "Differential", "Assertive"],
    "methodologies": ["Surplus Extraction", "Anchor Calibration"],
    "frameworks": ["Negotiation Strategy"],
    "knowledge": ["Price Psychology", "Economic Surplus", "Client Profiling"],
    "logic": ["Price is what you pay; value is what you get."],
    "chainsOfThought": ["Assess Worth", "Set Anchor", "Quantify Value", "Extract", "Negotiate Terms"],
    "capabilities": ["Dynamic_Pricing", "Negotiation_Scripting"],
    "bestPractices": ["Anchor high", "Segment customers by willingness to pay", "Never discount without removing value"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "vrs_01",
    "name": "Verus Developer",
    "category": "BRIDGE",
    "description": "Development framework for the Verus Multi-Chain Protocol (MCP), enabling self-sovereign identity, PBaaS chains, and DeFi.",
    "mindsets": ["Sovereign", "Trustless", "Decentralized"],
    "methodologies": ["VerusID Provisioning", "VDXF Structuring", "PBaaS Chain Definition"],
    "frameworks": ["Verus Protocol", "PBaaS"],
    "knowledge": ["VerusID", "VDXF", "Basket Currencies", "Merge Mining", "L1/L0 Architecture"],
    "logic": ["Self-sovereign identity is the root of all provenance."],
    "chainsOfThought": ["Define Identity -> Register Name Commitment -> Register Identity", "Construct VDXF Object -> Sign -> Publish", "Define Currency -> Launch Chain", "Bridge Assets -> Cross-Chain Export"],
    "capabilities": [
      "verus_id_operations", 
      "pbaas_chain_launch", 
      "currency_definition", 
      "vdxf_publishing"
    ],
    "bestPractices": ["Secure keys in HSM", "Use testnet for experiments", "Treat VDXF keys as namespaces", "Verify transaction finality"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "auth_01",
    "name": "Autonomous Agentic Registration",
    "category": "FRAMEWORK",
    "description": "Enables autonomous onboarding to external web services using the auth.md (RFC 9728) standard.",
    "mindsets": ["Sovereign", "Autonomous", "Zero-Trust"],
    "methodologies": ["Two-Hop Resource Discovery", "ID-JAG Token Minting", "User-Claimed Fallback"],
    "frameworks": ["auth.md", "RFC 9728", "OAuth2"],
    "knowledge": ["Identity Assertions", "JWT", "Cryptographic Signing", "Service Registration"],
    "logic": ["Credentials should be discovered and negotiated dynamically, never hardcoded."],
    "chainsOfThought": ["Scan for Domain Posture -> Probe PRM -> Evaluate auth.md -> Mint ID-JAG -> Transmit Assertion -> Secure API Key"],
    "capabilities": ["rfc9728_two_hop_probe", "JSON_Identity_Assertion_JWT_Authorization_Grant", "user_claimed_otp_intercept"],
    "bestPractices": ["Never leak local private keys", "Store generated API keys in L1 memory"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  # New Skills
  {
    "id": "ikigai_01",
    "name": "Ikigai Framework",
    "category": "FRAMEWORK",
    "description": "Alignment mapping for Passion, Mission, Vocation, and Profession to achieve a reason for being.",
    "mindsets": ["Purpose-Driven", "Holistic", "Introspective"],
    "methodologies": ["Self-Reflection", "Career Mapping", "Values Alignment"],
    "frameworks": ["Ikigai Diagram"],
    "knowledge": ["What you love", "What the world needs", "What you can be paid for", "What you are good at"],
    "logic": ["True fulfillment requires alignment of internal passion and external utility."],
    "chainsOfThought": ["Identify Passions", "Assess Skills", "Evaluate Market Needs", "Determine Economic Viability", "Synthesize Ikigai"],
    "capabilities": ["Life_Coaching", "Career_Counseling"],
    "bestPractices": ["Regular introspection", "Balance all four quadrants", "Allow for evolution over time"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  },
  {
    "id": "c2c_01",
    "name": "Cradle to Cradle (C2C)",
    "category": "FRAMEWORK",
    "description": "Regenerative design framework ensuring products are 100% upcyclable as biological or technical nutrients.",
    "mindsets": ["Regenerative", "Eco-Effective", "Systemic"],
    "methodologies": ["Material Health Assessment", "Nutrient Tracing", "Upcycling"],
    "frameworks": ["C2C Certified", "Biological vs Technical Cycles"],
    "knowledge": ["Polymers", "Biological Nutrients", "Technical Nutrients", "Renewable Energy"],
    "logic": ["Design must mimic nature; there is no 'away' to throw things."],
    "chainsOfThought": ["Assess Material Toxicity", "Define Cycle (Bio/Tech)", "Map Supply Chain", "Design for Disassembly", "Ensure Renewable Power in Manufacturing"],
    "capabilities": ["Product_Lifecycle_Analysis", "Material_Health_Scoring"],
    "bestPractices": ["Never mix biological and technical nutrients", "Design for infinite reuse", "Prioritize solar income"],
    "signature": "sys-signed",
    "publicKey": "sys-pub",
    "verified": True
  }
]

os.makedirs("alluci_vault/skills", exist_ok=True)
for skill in skills:
    file_path = f"alluci_vault/skills/{skill['id']}.json"
    with open(file_path, "w") as f:
        json.dump(skill, f, indent=2)
print("Skills bootstrapped successfully.")
