"""Health check endpoints for the Alluci Sovereign Agent.

Provides `/healthz` (liveness) and `/readyz` (readiness) routes that expose
component health information. These endpoints are deliberately lightweight
and suitable for Kubernetes probes.
"""

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse
# Import within endpoint to avoid circular import
# from .app import _check_health  # moved inside functions

router = APIRouter()


@router.get("/healthz", include_in_schema=False)
async def healthz(request: Request):
    """Liveness probe.

    Returns the comprehensive health dictionary generated by ``_check_health``.
    """
    from .app import _check_health
    return await _check_health(request.app)
@router.get("/health", include_in_schema=False)
async def health(request: Request):
    """Alias for /healthz, returns full health dict."""
    from .app import _check_health
    return await _check_health(request.app)


@router.get("/readyz", include_in_schema=False)
async def readyz(request: Request):
    """Readiness probe.

    Returns ``{"status": "ready"}`` when the overall system status is ``ok``;
    otherwise responds with HTTP 503 and the full health payload.
    """
    from .app import _check_health
    result = await _check_health(request.app)
    if result["status"] != "ok":
        return JSONResponse(status_code=503, content=result)
    return {"status": "ready"}
