#!/usr/bin/env python3
from __future__ import annotations

import datetime
import subprocess
from pathlib import Path
import os

ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)
TIMESTAMP = datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')
REPORT = REPORT_DIR / f"release_readiness_{TIMESTAMP}.md"

checks = [
    ("Preflight", ["bash", "scripts/production_readiness/preflight.sh"]),
    ("Quality", ["bash", "scripts/production_readiness/quality_gate.sh"]),
    ("Security", ["bash", "scripts/production_readiness/security_gate.sh"]),
    ("Deploy", ["bash", "scripts/production_readiness/deploy_gate.sh"]),
]

import tempfile

rows = []
for name, cmd in checks:
    print(f"Running {name} check...")
    with tempfile.TemporaryFile(mode="w+t", encoding="utf-8") as out_f, tempfile.TemporaryFile(mode="w+t", encoding="utf-8") as err_f:
        try:
            subprocess.run(cmd, cwd=ROOT, check=True, stdout=out_f, stderr=err_f, text=True)
            rows.append((name, "PASS", ""))
        except subprocess.CalledProcessError as exc:
            print(f"FAILED {name}")
            out_f.seek(0)
            err_f.seek(0)
            out_content = out_f.read()
            err_content = err_f.read()
            rows.append((name, f"FAIL ({exc.returncode})", err_content or out_content))

status = "PASS" if all(r[1] == "PASS" for r in rows) else "FAIL"

content = [
    "# Release Readiness Report",
    "",
    f"Generated: {datetime.datetime.now(datetime.timezone.utc).isoformat()}Z",
    f"Overall Status: **{status}**",
    "",
    "## Summary Table",
    "",
    "| Gate | Status | Details |",
    "|---|---|---|",
]
for name, res, detail in rows:
    detail_str = detail.replace("\n", "<br>").replace("|", "\\|")[:500] if detail else "OK"
    content.append(f"| {name} | {res} | {detail_str} |")

content.append("")
content.append("---")
content.append("Generated by Alluci Sovereign Agent Production Readiness Suite.")

REPORT.write_text("\n".join(content), encoding="utf-8")
print(f"\nReport generated at: {REPORT}")
if status == "FAIL":
    exit(1)
