"""add audit ledger and missing tables

Revision ID: 8d0c8354fde3
Revises: 24ca23f2c29c
Create Date: 2026-06-13 09:41:06.817547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8d0c8354fde3'
down_revision: Union[str, None] = '24ca23f2c29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Monkey patch batch_alter_table to safely check for table, column, and index existence
_orig_batch_alter_table = op.batch_alter_table

import contextlib
@contextlib.contextmanager
def safe_batch_alter_table(table_name, schema=None, **kw):
    bind = op.get_bind()
    import sqlalchemy as sa
    inspector = sa.inspect(bind)
    
    if not inspector.has_table(table_name, schema=schema):
        class DummyBatchOp:
            def __getattr__(self, name):
                return lambda *args, **kwargs: None
        yield DummyBatchOp()
        return

    columns = {c['name'] for c in inspector.get_columns(table_name, schema=schema)}
    indexes = {idx['name'] for idx in inspector.get_indexes(table_name, schema=schema)}
    
    with _orig_batch_alter_table(table_name, schema=schema, **kw) as batch_op:
        class SafeBatchOp:
            def drop_column(self, col_name, **kw):
                if col_name in columns:
                    batch_op.drop_column(col_name, **kw)
            def drop_index(self, idx_name, **kw):
                if idx_name in indexes:
                    batch_op.drop_index(idx_name, **kw)
            def __getattr__(self, name):
                return getattr(batch_op, name)
        yield SafeBatchOp()

op.batch_alter_table = safe_batch_alter_table


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcl_world_model_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'queued_task' not in inspector.get_table_names():
        op.create_table('queued_task',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'PENDING', 'SKIPPED', 'SUSPENDED_SECURITY', name='taskstatus'), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('checkpoint', sa.JSON(), nullable=True),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table('task_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_dag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_record_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_record_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_record_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('agent_channel_subscription', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_agent_channel_subscription_channel_id'), ['channel_id'], unique=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('agent_record', schema=None) as batch_op:
        batch_op.alter_column('fallback_chain',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('heartbeat_orders',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('soul_manifest_override',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_agent_record_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_record_status'), ['status'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verus_txid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('vdxf_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('anchored_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('ix_audit_log_event')
        batch_op.drop_index('ix_audit_log_timestamp')
        batch_op.create_index(batch_op.f('ix_audit_log_vdxf_key'), ['vdxf_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_verus_txid'), ['verus_txid'], unique=False)
        batch_op.drop_column('phi_total')
        batch_op.drop_column('betti')
        batch_op.drop_column('pvt_json')
        batch_op.drop_column('psi')
        batch_op.drop_column('key_id')
        batch_op.drop_column('event')
        batch_op.drop_column('coherence')
        batch_op.drop_column('details')
        batch_op.drop_column('merkle_attribution_hash')
        batch_op.drop_column('hmac_signature')

    with op.batch_alter_table('cron_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('payload',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('thinking_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('delivery_account_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.drop_index('ix_cron_run_job_id')
        batch_op.drop_column('log_text')
        batch_op.drop_column('finished_at')
        batch_op.drop_column('delivery_status')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_device_public_key')
        batch_op.drop_index('ix_device_fingerprint')
        batch_op.create_index(batch_op.f('ix_device_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('device_binding', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_device_binding_device_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('goal_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_record_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_record_title'), ['title'], unique=False)

    with op.batch_alter_table('heartbeat_order_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.alter_column('fired_at',
               existing_type=sa.FLOAT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('probe_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('ix_heartbeat_order_record_agent_id')
        batch_op.drop_index('ix_heartbeat_order_record_fired_at')
        batch_op.create_foreign_key('fk_heartbeat_order_record_agent_id', 'agent_record', ['agent_id'], ['id'])

    with op.batch_alter_table('hlsm_episodic', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True)
        batch_op.alter_column('extra_metadata',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('ix_hlsm_episodic_objective_hash')
        batch_op.drop_index('ix_hlsm_episodic_session_key')
        batch_op.drop_index('ix_hlsm_episodic_source')

    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('cache_read_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cache_write_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('pcl_opportunity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.FLOAT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('actioned_at',
               existing_type=sa.FLOAT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_pcl_opportunity_detector_name')
        batch_op.drop_index('ix_pcl_opportunity_detector')
        batch_op.drop_column('objective')
        batch_op.drop_column('detector_name')
        batch_op.drop_column('title')
        batch_op.drop_column('confidence')
        batch_op.drop_column('autonomy_level')
        batch_op.drop_column('notification_body')
        batch_op.drop_column('priority')
        batch_op.drop_column('requires_approval')
        batch_op.drop_column('recommended_action')
        batch_op.drop_column('cycle_number')
        batch_op.drop_column('user_engaged')
        batch_op.drop_column('cooldown_minutes')
        batch_op.drop_column('affects_goal_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('presence_beacon', schema=None) as batch_op:
        batch_op.drop_index('ix_presence_beacon_client_id')
        batch_op.drop_index('ix_presence_beacon_last_seen')
        batch_op.create_index(batch_op.f('ix_presence_beacon_subject'), ['subject'], unique=False)
        batch_op.drop_column('data_fields')
        batch_op.drop_column('id')

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('ix_run_agent_id')

    with op.batch_alter_table('session_config', schema=None) as batch_op:
        batch_op.alter_column('thinking_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('verbose_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('reasoning_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('ix_session_config_session_key')
        batch_op.create_index(batch_op.f('ix_session_config_session_key'), ['session_key'], unique=False)

    with op.batch_alter_table('sop_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_record_name'), ['name'], unique=False)

    op.drop_table('channel_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sop_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_record_name'))

    with op.batch_alter_table('session_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_config_session_key'))
        batch_op.create_index('ix_session_config_session_key', ['session_key'], unique=1)
        batch_op.alter_column('reasoning_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('verbose_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('thinking_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('ix_run_agent_id', ['agent_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('presence_beacon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('data_fields', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_presence_beacon_subject'))
        batch_op.create_index('ix_presence_beacon_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('ix_presence_beacon_client_id', ['client_id'], unique=1)

    with op.batch_alter_table('pcl_opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('affects_goal_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cooldown_minutes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_engaged', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('cycle_number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('recommended_action', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('requires_approval', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('notification_body', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('autonomy_level', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('detector_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('objective', sa.VARCHAR(), nullable=False))
        batch_op.create_index('ix_pcl_opportunity_detector_name', ['detector_name'], unique=False)
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('actioned_at',
               existing_type=sa.DateTime(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.DateTime(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.alter_column('cache_write_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cache_read_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('hlsm_episodic', schema=None) as batch_op:
        batch_op.create_index('ix_hlsm_episodic_source', ['source'], unique=False)
        batch_op.create_index('ix_hlsm_episodic_session_key', ['session_key'], unique=False)
        batch_op.create_index('ix_hlsm_episodic_objective_hash', ['objective_hash'], unique=False)
        batch_op.alter_column('extra_metadata',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('heartbeat_order_record', schema=None) as batch_op:
        batch_op.create_index('ix_heartbeat_order_record_fired_at', ['fired_at'], unique=False)
        batch_op.create_index('ix_heartbeat_order_record_agent_id', ['agent_id'], unique=False)
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('probe_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fired_at',
               existing_type=sa.DateTime(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('order')

    with op.batch_alter_table('goal_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_record_title'))
        batch_op.drop_index(batch_op.f('ix_goal_record_status'))

    with op.batch_alter_table('device_binding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.create_index('ix_device_binding_device_id', ['device_id'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_device_name'))
        batch_op.drop_index(batch_op.f('ix_device_fingerprint'))
        batch_op.create_index('ix_device_fingerprint', ['fingerprint'], unique=1)
        batch_op.create_index('ix_device_public_key', ['public_key'], unique=1)
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('log_text', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_cron_run_job_id', ['job_id'], unique=False)

    with op.batch_alter_table('cron_job', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cron_job_delivery_account_id', 'channel_account', ['delivery_account_id'], ['id'])
        batch_op.alter_column('delivery_account_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('thinking_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('payload',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hmac_signature', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('merkle_attribution_hash', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('coherence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('event', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('key_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('psi', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pvt_json', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('betti', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phi_total', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_log_verus_txid'))
        batch_op.drop_index(batch_op.f('ix_audit_log_vdxf_key'))
        batch_op.create_index('ix_audit_log_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_log_event', ['event'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('data')
        batch_op.drop_column('anchored_timestamp')
        batch_op.drop_column('vdxf_key')
        batch_op.drop_column('verus_txid')

    with op.batch_alter_table('agent_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_record_status'))
        batch_op.drop_index(batch_op.f('ix_agent_record_name'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('soul_manifest_override',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('heartbeat_orders',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('fallback_chain',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('agent_channel_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_agent_channel_subscription_channel_id'))
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('channel_account',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_record_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_record_status'))
        batch_op.drop_index(batch_op.f('ix_task_record_run_id'))

    op.drop_table('task_record')
    op.drop_table('queued_task')
    op.drop_table('pcl_world_model_snapshot')
    # ### end Alembic commands ###
