"""Sync v6.4 production schema

Revision ID: 8f15288273f9
Revises: d1e2f3a4b5c6
Create Date: 2026-03-24 13:10:44.309134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8f15288273f9'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_record', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('system_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('heartbeat_orders',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('soul_manifest_override',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_agent_record_status'))

    # Redundant drop handled in ed12bc369d08
    # with op.batch_alter_table('channel_account', schema=None) as batch_op:
    #     batch_op.drop_column('credentials')

    with op.batch_alter_table('goal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('heartbeat_order_record', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.drop_index('ix_hb_order_agent_id')
        batch_op.drop_index('ix_hb_order_fired_at')
        batch_op.drop_index('ix_hb_order_order_id')
        batch_op.create_index(batch_op.f('ix_heartbeat_order_record_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heartbeat_order_record_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_heartbeat_order_record_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heartbeat_order_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heartbeat_order_record_order_id'))
        batch_op.drop_index(batch_op.f('ix_heartbeat_order_record_fired_at'))
        batch_op.drop_index(batch_op.f('ix_heartbeat_order_record_agent_id'))
        batch_op.create_index(batch_op.f('ix_hb_order_record_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_order_record_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_order_record_agent_id'), ['agent_id'], unique=False)
        batch_op.alter_column('detail',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('goal_record', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('agent_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_record_status'), ['status'], unique=False)
        batch_op.alter_column('soul_manifest_override',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('heartbeat_orders',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
