"""add agent_channel_subscription

Revision ID: e7a1b2c3d4e5
Revises: d5383825d624
Create Date: 2026-03-17 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'e7a1b2c3d4e5'
down_revision = 'd5383825d624'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_channel_subscription',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_id', 'channel_id', name='uq_agent_channel')
    )
    op.create_index(op.f('ix_agent_channel_subscription_agent_id'), 'agent_channel_subscription', ['agent_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_channel_subscription_agent_id'), table_name='agent_channel_subscription')
    op.drop_table('agent_channel_subscription')
    # ### end Alembic commands ###
