"""add_sprint_1_6_tables

Revision ID: d5383825d624
Revises: cc9ee558fe12
Create Date: 2026-03-13 18:08:11.977142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5383825d624'
down_revision: Union[str, Sequence[str], None] = 'cc9ee558fe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('integrity_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('channel_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_account_account_identifier'), ['account_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_channel_account_channel_type'), ['channel_type'], unique=False)

    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_public_key'), ['public_key'], unique=True)

    op.create_table('discord_guild_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guild_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discord_guild_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_guild_mapping_guild_id'), ['guild_id'], unique=True)

    op.create_table('exec_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exec_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exec_policy_tool_name'), ['tool_name'], unique=False)

    op.create_table('goal_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_target', sa.Float(), nullable=True),
    sa.Column('metric_current', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_args', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_log_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_session_key'), ['session_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('output_price_per_1m', sa.Float(), nullable=False),
    sa.Column('cache_read_price', sa.Float(), nullable=False),
    sa.Column('cache_write_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_pricing_model_id'), ['model_id'], unique=True)

    op.create_table('presence_beacon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_fields', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_beacon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_beacon_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_presence_beacon_last_seen'), ['last_seen'], unique=False)

    op.create_table('session_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thinking_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verbose_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasoning_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_config_session_key'), ['session_key'], unique=True)

    op.create_table('sop_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read', sa.Integer(), nullable=False),
    sa.Column('cache_write', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_log_session_key'), ['session_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('cron_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thinking_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_account_id', sa.Integer(), nullable=True),
    sa.Column('delivery_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_context', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_account_id'], ['channel_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('device_binding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_binding_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_binding_device_id'), ['device_id'], unique=False)

    op.create_table('cron_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('log_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['cron_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cron_run_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cron_run_job_id'))

    op.drop_table('cron_run')
    with op.batch_alter_table('device_binding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_binding_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_binding_agent_id'))

    op.drop_table('device_binding')
    op.drop_table('cron_job')
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usage_log_session_key'))

    op.drop_table('usage_log')
    op.drop_table('sop_record')
    with op.batch_alter_table('session_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_config_session_key'))

    op.drop_table('session_config')
    with op.batch_alter_table('presence_beacon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_beacon_last_seen'))
        batch_op.drop_index(batch_op.f('ix_presence_beacon_client_id'))

    op.drop_table('presence_beacon')
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_pricing_model_id'))

    op.drop_table('model_pricing')
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_log_session_key'))
        batch_op.drop_index(batch_op.f('ix_message_log_account_id'))

    op.drop_table('message_log')
    op.drop_table('goal_record')
    with op.batch_alter_table('exec_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exec_policy_tool_name'))

    op.drop_table('exec_policy')
    with op.batch_alter_table('discord_guild_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_guild_mapping_guild_id'))

    op.drop_table('discord_guild_mapping')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_public_key'))
        batch_op.drop_index(batch_op.f('ix_device_fingerprint'))

    op.drop_table('device')
    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_account_channel_type'))
        batch_op.drop_index(batch_op.f('ix_channel_account_account_identifier'))

    op.drop_table('channel_account')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
