"""verify

Revision ID: ed12bc369d08
Revises: e7a1b2c3d4e5
Create Date: 2026-03-18 10:07:58.686743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ed12bc369d08'
down_revision: Union[str, Sequence[str], None] = 'e7a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_channel_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agent_channel'), type_='unique')

    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.drop_column('credentials')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('agent_channel_subscription', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_agent_channel'), ['agent_id', 'channel_id'])

    # ### end Alembic commands ###
